### ISSUE TITLE
Just one more datapoint: hygienic 'threading'

### ISSUE THREAD

**Issue by Metaxal** [rogerkeays/racket-fluent#3]
Hi,

Your readme is a nice and short reflection on the subject and fun to read, thanks :)

Personally, I like to maintain hygiene when it's easy to do so:
https://gist.github.com/Metaxal/e85c19acd3de0069fbe4f84b01491049

I also find this more intuitive, easier to read and more flexible than `~>` and `~~>`.

**Comment by rogerkeays** [comment]
Thanks for the feedback. Can you give me an example of how fluent breaks hygiene? I think I might be missing something.

Prefix macros like the one you linked to are quite nice. One of the advantages of using infix syntax is that the parens around each step can be left out. Personal preference really... or maybe just what you're used to (I got used to unix pipes).

**Comment by Metaxal** [comment]
I only read the README, but I inferred (wrongly, it seems) that you were also using 'hole markers' like `_` (e.g., https://docs.racket-lang.org/threading/index.html). But your lambda shortcut is better.

That said, I still prefer to have an explicit identifier (which avoids the repetition of `(x : ...)`), but this is all just a matter of taste really, as you say :)

**Comment by Metaxal** [comment]
I'm closing this as it was just a remark in passing, not really any issue per se.
